import keymirror from 'keymirror';

export default keymirror({
  CREATE_USER: null,
  LOGIN_USER: null,
  SET_LOGGED_IN_USER_DETAILS: null,
  IS_LOGGED_IN: null,
  LOGIN_USER_ERROR: null,
  CREATE_DOCUMENT_SUCCESS: null,
  LOAD_DOCUMENTS_SUCCESS: null,
  LOAD_DOCUMENT_SUCCESS: null,
  DOCUMENT_DELETED_SUCCESSFULLY: null,
  UNDO_DELETED_ITEM: null,
  LOAD_USERS_SUCCESSFUL: null,
  LOAD_ALL_DOCUMENTS_SUCCESS: null,
  CHANGE_SEARCH_LOCATION: null,
  CHANGE_SEARCH_QUERY: null,
});
